version: "2.1"
services:
  db:
    container_name: 'db'
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE : 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'db'] ## to wait for the db to start before running the application
      timeout: 20s
      retries: 2
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

