version: "2.1"
services:
  db:
    container_name: 'db'
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE : 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'db'] ## to wait for the db to start before running the application
      timeout: 20s
      retries: 2